config/routes.rb
Rails.application.routes.draw do
  get 'items/index'
  get 'items/new'
  root to: 'items#index'
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'FACE' },
    { id: 3, name: 'EYE' },
    { id: 4, name: 'LIP' }
  ]
  include ActiveHash::Associations
  has_many :items
end

app/models/category_option.rb
class CategoryOption < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'ベース' },
    { id: 3, name: 'ファンデーション' },
    { id: 4, name: 'コンシーラー' },
    { id: 5, name: 'パウダー' },
    { id: 6, name: 'チーク' },
    { id: 7, name: 'シェーディング' },
    { id: 8, name: 'ハイライター' },

    { id: 9, name: 'アイシャドウ' },
    { id: 10, name: 'アイライナー' },
    { id: 11, name: 'マスカラ' },
    { id: 12, name: 'アイブロウ' },

    { id: 13, name: 'リップスティック' },
    { id: 14, name: 'リキッドリップ' },
    { id: 15, name: 'リップグロス' },
    { id: 16, name: 'リップティント' },
    { id: 17, name: 'リップペンシル' },
    { id: 18, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :category_option
  has_one_attached :image

  with_options presence: true do
    validates :image, blob: { content_type: :image }
    validates :title, :content, :start_date
    validates :category_id, :category_option_id, numericality: { other_than: 1, message: "can't be blank" }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all.order('created_at DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :title, :content, :category_id, :category_option_id, :start_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_error_messages.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/items/index.html.erb
<div class="main">
  <%# TOPイメージ部分 %>
  <div class="title-content">
    <div class="service-concept">
    <%= image_tag "cosmit-top.png", class:"top-img" %>
    </div>
  </div>
  <%# /TOPイメージ部分 %>

  <%# コスメ一覧 %>
  <div class="item-contents">
    <h4 class="title">Cosmetic list</h4>
      <ul class="item-lists">
        <% @items.each do |item| %>
          <li class='list'>
            <%#= link_to item_path(item.id) do %>
              <div class='item-img-content'>
                <%= image_tag item.image, class: "item-img" if item.image.attached? %>
              </div>
              <div class="item-info">
                <h3 class="item-name">
                  <%= item.title %>
                </h3>
                <div class="item-category">
                  <%= item.category_option.name %>
                </div>
              </div>
          </li>
        <% end %>
      </ul>
  </div>
  <%# /コスメ一覧 %>
</div>

app/views/items/new.html.erb
<div class="item-container">
  <div class="item-area">
    <h2 class="item-title">コスメ内容を入力</h2>
    <%= form_with model: @item, url:items_path, local: true do |f| %>

    <%= render 'error_messages', model: f.object %>
    <%# コスメ画像%>
    <div class="img-upload">
      <div class="weight-bold-text">
      コスメ画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
        クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# カテゴリー、コスメ名,フリーワード %>
    <div class="new-items">
      <div class="items-category1">
        <div class="weight-bold-text">カテゴリー1
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
      <div class="items-category2">
        <div class="weight-bold-text">カテゴリー2
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_option_id, CategoryOption.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
      <div class="item-name">
        <div class="weight-bold-text">コスメ名
        <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :title, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
    </div>
    <div class="item-content">
      <div class="weight-bold-text">内容
      <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :content, class:"items-text", id:"item-info", placeholder:"特徴・使用感など", rows: "10"%>
    </div>
    <div class="item-start-date">
      <div class="weight-bold-text">使用開始日
      <span class="indispensable">必須</span>
      </div>
      <%= f.date_field :start_date, class: 'item-date' %>
    </div>
    <div class="item-btn">
      <%= f.submit "SEND" , class:"item-color-btn"%>
    </div>

  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cosmit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Yuji+Boku&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="header">
      <div class="header__bar">
        <h1 class="header-logo"><a href="/">Cosmit</a></h1>
        <div class="header-nav__list">
          <div class="nav-user">
          </div>
          <a class="post" href="/items/new">登録する</a>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>